FROM golang:latest as builder

WORKDIR /app

COPY . .

# remover o debug do GO para produção -ldflags="-w -s"
#CGO_ENABLED=0 desabilita o compilador C
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-w -s" -o main . 

FROM scratch

COPY --from=builder /app/main .

CMD ["./main"]